# Code Written by:
**Shweta Tiwari**
*20 Oct 2023*

## Algorithm: Roots of Polynomial

In [1]:
import time

In [2]:
import numpy as np

# Algorithm

In [3]:
%%time
def roots(*coeffs):
    matrix = np.eye(len(coeffs) - 1, k=-1)
    matrix[:,-1] = np.array(coeffs[:0:-1]) / -coeffs[0]
    return np.linalg.eigvals(matrix)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 9.78 µs


# Run

In [4]:
%%time
# 10x - 1 = 0
roots(10, -1)

CPU times: user 1.67 ms, sys: 0 ns, total: 1.67 ms
Wall time: 12.8 ms


array([0.1])

In [5]:
%%time
# x^2 - 2x + 1 = 0
roots(1, -2, 1)

CPU times: user 1.15 ms, sys: 0 ns, total: 1.15 ms
Wall time: 7.33 ms


array([1., 1.])

In [6]:
%%time
# 2x^2 - 18 = 0
roots(2, 0, -18)

CPU times: user 284 µs, sys: 0 ns, total: 284 µs
Wall time: 299 µs


array([ 3., -3.])

In [7]:
%%time
# x^5 + x^4 + x^3 + x^2 + x + 1 = 0
roots(1, 1, 1, 1, 1, 1)

CPU times: user 226 µs, sys: 46 µs, total: 272 µs
Wall time: 281 µs


array([ 0.5+0.8660254j,  0.5-0.8660254j, -1. +0.j       , -0.5+0.8660254j,
       -0.5-0.8660254j])

# The End