# Code Written by:
**Shweta Tiwari**
*20 Oct 2023*

## Algorithm:  Conjugate Gradients

In [1]:
import time

In [2]:
import numpy as np

# Algorithm

In [3]:
%%time
def conjugate_gradients(A, b):
    x = np.zeros(A.shape[1])
    residuals = b - A @ x
    direction = residuals
    error = residuals.T @ residuals

    # step along conjugate directions
    while error > 1e-8:
        x += direction * error / (direction.T @ A @ direction)
        residuals = b - A @ x
        error1 = error
        error = residuals.T @ residuals
        direction = residuals + error / error1 * direction

    return x

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 10.3 µs


# Run

In [4]:
%%time
A = np.random.rand(5, 3)
b = np.random.rand(5)

print('A')
print(A)
print('b')
print(b)
print('x')

# make system positive semidefinite
print(conjugate_gradients(A.T @ A, A.T @ b))

A
[[0.9924999  0.59339143 0.89190161]
 [0.06078578 0.61334418 0.67440281]
 [0.15092663 0.44222482 0.57292133]
 [0.97840647 0.78998228 0.94092986]
 [0.31052376 0.175385   0.2032473 ]]
b
[0.99496486 0.53498513 0.71876102 0.88766472 0.00735163]
x
[-0.1910128  -1.86673124  2.62064496]
CPU times: user 4.86 ms, sys: 1.04 ms, total: 5.9 ms
Wall time: 13.2 ms


# The End