# Code Written by:
**Shweta Tiwari**
*20 Oct 2023*

## Algorithm:  Strassen Multiplication

In [1]:
import time

In [2]:
import numpy as np

# Algorithm

In [3]:
%%time
def strassen(A, B):
    k = A.shape[0] // 2
    if k == 0:
        return A * B

    A11, A12 = A[:k, :k], A[:k, k:]
    A21, A22 = A[k:, :k], A[k:, k:]
    B11, B12 = B[:k, :k], B[:k, k:]
    B21, B22 = B[k:, :k], B[k:, k:]

    T1 = strassen(A11 + A22, B11 + B22)
    T2 = strassen(A21 + A22, B11)
    T3 = strassen(A11, B12 - B22)
    T4 = strassen(A22, B21 - B11)
    T5 = strassen(A11 + A12, B22)
    T6 = strassen(A21 - A11, B11 + B12)
    T7 = strassen(A12 - A22, B21 + B22)

    C = np.zeros(A.shape, dtype=A.dtype)
    C[:k, :k] = T1 + T4 - T5 + T7
    C[:k, k:] = T3 + T5
    C[k:, :k] = T2 + T4
    C[k:, k:] = T1 - T2 + T3 + T6

    return C

CPU times: user 0 ns, sys: 4 µs, total: 4 µs
Wall time: 6.68 µs


# Run

In [4]:
%%time
X = np.random.randint(0, 10, (8, 8))
X

CPU times: user 227 µs, sys: 46 µs, total: 273 µs
Wall time: 3.73 ms


array([[5, 8, 4, 9, 7, 1, 1, 9],
       [9, 5, 6, 4, 6, 3, 6, 9],
       [6, 8, 9, 2, 4, 3, 5, 1],
       [4, 4, 6, 2, 3, 9, 3, 7],
       [1, 7, 6, 3, 3, 1, 6, 0],
       [6, 2, 2, 9, 9, 4, 7, 1],
       [7, 9, 2, 8, 8, 0, 6, 5],
       [5, 2, 8, 0, 1, 0, 1, 2]])

In [5]:
%%time
Y = np.random.randint(0, 10, (8, 8))
Y

CPU times: user 159 µs, sys: 0 ns, total: 159 µs
Wall time: 165 µs


array([[2, 5, 0, 5, 8, 4, 5, 7],
       [5, 6, 5, 9, 1, 2, 3, 4],
       [0, 3, 2, 9, 8, 1, 2, 5],
       [8, 0, 3, 6, 9, 7, 9, 1],
       [8, 7, 3, 7, 7, 8, 5, 5],
       [6, 1, 9, 9, 6, 6, 0, 1],
       [0, 5, 5, 9, 4, 2, 0, 9],
       [6, 5, 6, 7, 8, 3, 4, 2]])

In [6]:
%%time
strassen(X, Y)

CPU times: user 4.11 ms, sys: 0 ns, total: 4.11 ms
Wall time: 5.98 ms


array([[238, 185, 164, 317, 292, 194, 209, 159],
       [195, 213, 178, 354, 317, 185, 174, 222],
       [124, 166, 134, 302, 220, 126, 114, 191],
       [164, 142, 185, 300, 245, 149, 105, 141],
       [ 91, 117, 104, 224, 141,  87,  80, 138],
       [196, 155, 145, 289, 270, 206, 170, 183],
       [217, 206, 157, 327, 273, 195, 198, 207],
       [ 40,  83,  46, 145, 133,  48,  60, 101]])

# The End