# Code Written by:
**Shweta Tiwari**
*20 Oct 2023*

## Algorithm:  Gradient Approximation

In [1]:
import time

In [2]:
import numpy as np

# Algorithm

In [3]:
%%time
def gradient(fun, x, delta=1e-4):
    x = np.asfarray(x)
    grad = np.zeros(x.shape, dtype=x.dtype)

    for i, t in np.ndenumerate(x):
        x[i] = t + delta
        grad[i] = fun(x)
        x[i] = t - delta
        grad[i] -= fun(x)
        x[i] = t

    return grad / (2 * delta)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.15 µs


# Run

## Quadratic Form

In [4]:
%%time
def function(x):
    return 3 * x**2 + 2 * x + 1

for x in [-1, 0, 1]:
    print('x=', x, 'grad=', gradient(function, [x]))

x= -1 grad= [-4.]
x= 0 grad= [2.]
x= 1 grad= [8.]
CPU times: user 1.94 ms, sys: 0 ns, total: 1.94 ms
Wall time: 1.95 ms


## Transcendental Function

In [5]:
%%time
def function(X):
    x, y, z = X
    return x * np.sin(z) + y * np.cos(z) + z * np.exp(x + y)

for x in [[0, 0, 0], [0, 0, 1], [0, 1, 1], [1, 1, 1]]:
    print('x=', x, 'grad=', gradient(function, x))

x= [0, 0, 0] grad= [0. 1. 1.]
x= [0, 0, 1] grad= [1.84147099 1.54030231 1.        ]
x= [0, 1, 1] grad= [3.55975282 3.25858414 1.87681085]
x= [1, 1, 1] grad= [8.2305271  7.92935842 7.08788742]
CPU times: user 1.94 ms, sys: 82 µs, total: 2.03 ms
Wall time: 6.28 ms


## Determinant

In [6]:
%%time
function = np.linalg.det

for x in [
    [[1, 2, 3], [2, 3, 1], [3, 1, 2]],
    [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
    [[1, 1], [1, 1]],
]:
    print('x=')
    print(x)
    print('grad=')
    print(gradient(function, x))

x=
[[1, 2, 3], [2, 3, 1], [3, 1, 2]]
grad=
[[ 5. -1. -7.]
 [-1. -7.  5.]
 [-7.  5. -1.]]
x=
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
grad=
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
x=
[[1, 1], [1, 1]]
grad=
[[ 1. -1.]
 [-1.  1.]]
CPU times: user 2.28 ms, sys: 0 ns, total: 2.28 ms
Wall time: 4.04 ms


# The End