# Code Written by:
**Shweta Tiwari**
*20 Oct 2023*

## Algorithm:  Gram Schmidt

In [1]:
import time

In [2]:
import numpy as np

# Algorithm

In [3]:
%%time
def gram_schmidt(X):
    O = np.zeros(X.shape)

    for i in range(X.shape[1]):
        # orthogonalization
        vector = X[:, i]
        space = O[:, :i]
        projection = vector @ space
        vector = vector - np.sum(projection * space, axis=1)

        # normalization
        norm = np.sqrt(vector @ vector)
        vector /= abs(norm) < 1e-8 and 1 or norm

        O[:, i] = vector

    return O

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 9.54 µs


# Run

In [4]:
%%time
# 6 column vectors in 4D
vectors = np.array([
    [1, 1, 2, 0, 1, 1],
    [0, 0, 0, 1, 2, 1],
    [1, 2, 3, 1, 3, 2],
    [1, 0, 1, 0, 1, 1]
], dtype=float)

CPU times: user 29 µs, sys: 4 µs, total: 33 µs
Wall time: 37 µs


In [5]:
%%time
# check orthogonality
vectors.T @ vectors

CPU times: user 0 ns, sys: 282 µs, total: 282 µs
Wall time: 2.99 ms


array([[ 3.,  3.,  6.,  1.,  5.,  4.],
       [ 3.,  5.,  8.,  2.,  7.,  5.],
       [ 6.,  8., 14.,  3., 12.,  9.],
       [ 1.,  2.,  3.,  2.,  5.,  3.],
       [ 5.,  7., 12.,  5., 15., 10.],
       [ 4.,  5.,  9.,  3., 10.,  7.]])

In [6]:
%%time
orthonormal = gram_schmidt(vectors)
orthonormal.round(5)

CPU times: user 1.28 ms, sys: 42 µs, total: 1.32 ms
Wall time: 3.09 ms


array([[ 0.57735, -0.     , -0.     , -0.30861,  0.     , -0.     ],
       [ 0.     ,  0.     ,  0.     ,  0.92582,  0.     ,  0.     ],
       [ 0.57735,  0.70711,  0.     ,  0.1543 ,  0.     ,  0.     ],
       [ 0.57735, -0.70711, -0.     ,  0.1543 , -0.     , -0.     ]])

In [7]:
%%time
# check orthogonality
(orthonormal.T @ orthonormal).round(5)

CPU times: user 81 µs, sys: 12 µs, total: 93 µs
Wall time: 97.8 µs


array([[ 1., -0., -0., -0.,  0., -0.],
       [-0.,  1.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  0.,  0.,  0.,  0.,  0.]])

## QR decomposition

In [8]:
%%time
matrix = np.array([
    [1, 1, -1],
    [1, 2, 1],
    [1, 3, 0]
], dtype=float)

CPU times: user 36 µs, sys: 6 µs, total: 42 µs
Wall time: 59.6 µs


In [9]:
%%time
Q = gram_schmidt(matrix)
Q.round(5)

CPU times: user 339 µs, sys: 0 ns, total: 339 µs
Wall time: 348 µs


array([[ 0.57735, -0.70711, -0.40825],
       [ 0.57735, -0.     ,  0.8165 ],
       [ 0.57735,  0.70711, -0.40825]])

In [10]:
%%time
R = Q.T @ matrix
R.round(5)

CPU times: user 237 µs, sys: 0 ns, total: 237 µs
Wall time: 1.2 ms


array([[ 1.73205,  3.4641 ,  0.     ],
       [-0.     ,  1.41421,  0.70711],
       [ 0.     ,  0.     ,  1.22474]])

In [11]:
%%time
 (Q @ R).round(5)

CPU times: user 72 µs, sys: 11 µs, total: 83 µs
Wall time: 87.7 µs


array([[ 1.,  1., -1.],
       [ 1.,  2.,  1.],
       [ 1.,  3., -0.]])

# The End