# Code Written by:
**Shweta Tiwari**
*20 Oct 2023*

## Algorithm: Hopfield Net

In [1]:
import time

In [2]:
import numpy as np

# Algorithm

In [3]:
%%time
def hopfield_net(n):
    weights = np.zeros((n, n), dtype=int)

    def _store(data):
        nonlocal weights

        vector = np.array(data, dtype=int) * 2 - 1
        weights += np.outer(vector, vector) - np.eye(len(data), dtype=int)

    def _reconstruct(data):
        visible = np.array(data, dtype=int)

        while True:
            for i, v in np.ndenumerate(visible):
                visible[i] = weights[i] @ visible >= 0

            hidden = weights @ visible >= 0
            if np.all(hidden == visible):
                return visible

    return _store, _reconstruct

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.44 µs


# Run

In [4]:
%%time
store, reconstruct = hopfield_net(25)

CPU times: user 20 µs, sys: 3 µs, total: 23 µs
Wall time: 27.4 µs


## Memories

In [5]:
%%time
store([
    1,0,0,0,1,
    0,1,0,1,0,
    0,0,1,0,0,
    0,1,0,1,0,
    1,0,0,0,1,
])

CPU times: user 1.08 ms, sys: 12 µs, total: 1.1 ms
Wall time: 3.89 ms


In [6]:
%%time
store([
    1,1,1,1,1,
    1,0,0,0,1,
    1,0,0,0,1,
    1,0,0,0,1,
    1,1,1,1,1,
])

CPU times: user 548 µs, sys: 0 ns, total: 548 µs
Wall time: 753 µs


In [7]:
%%time
store([
    0,0,1,0,0,
    0,0,1,0,0,
    1,1,1,1,1,
    0,0,1,0,0,
    0,0,1,0,0,
])

CPU times: user 488 µs, sys: 0 ns, total: 488 µs
Wall time: 498 µs


## Reconstruction

In [8]:
%%time
reconstruct([
    1,1,1,1,1,
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,0,
]).reshape(5, 5)

CPU times: user 798 µs, sys: 0 ns, total: 798 µs
Wall time: 952 µs


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [9]:
%%time
reconstruct([
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,0,
    0,0,0,0,1,
    1,1,0,0,1,
]).reshape(5, 5)

CPU times: user 1.58 ms, sys: 0 ns, total: 1.58 ms
Wall time: 2.66 ms


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [10]:
%%time
reconstruct([
    1,0,0,0,0,
    0,1,0,0,0,
    0,0,1,0,0,
    0,0,0,1,0,
    0,0,0,0,1,
]).reshape(5, 5)

CPU times: user 277 µs, sys: 0 ns, total: 277 µs
Wall time: 293 µs


array([[1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1]])

In [11]:
%%time
reconstruct([
    0,0,0,0,0,
    0,0,1,0,0,
    0,1,0,1,0,
    0,0,1,0,0,
    0,0,0,0,0,
]).reshape(5, 5)

CPU times: user 224 µs, sys: 32 µs, total: 256 µs
Wall time: 331 µs


array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [12]:
%%time
reconstruct([
    0,0,1,0,0,
    0,0,1,0,0,
    0,0,1,0,0,
    0,0,1,0,0,
    0,0,1,0,0,
]).reshape(5, 5)

CPU times: user 210 µs, sys: 29 µs, total: 239 µs
Wall time: 246 µs


array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

# The End